### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ivastar** [ivastar/grizli#3]
Start of a thread with installation issues.

**Comment by BSGalvan** [comment]
Not an issue as such, but `pip install -e . -r requirements.py` creates `grizli/version.py` which is just this:
``` python
# git describe --tags
__version__ = ""
__long_version__ = ""
__version_hash__ = "---"
```

Edit: This is an error on my part, since I didn't fetch all the tags from the upstream repo into my local. Note to self for [how to do this](https://stackoverflow.com/questions/51006930/upstream-git-tag-is-not-showing-in-forked-repository).

Edit: There might be a niftier way to do this, using [setuptools_scm](https://github.com/pypa/setuptools_scm). This is what [astropy uses](https://github.com/astropy/astropy/blob/main/pyproject.toml#L11).

**Comment by ivastar** [comment]
Done.
